# Generated by Django 5.0.6 on 2024-06-26 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoriya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriya',
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255)),
                ('tavsif', models.TextField()),
                ('narxi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time', models.DateTimeField(auto_now=True)),
                ('kategoriya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulot',
            },
        ),
        migrations.CreateModel(
            name='mahsulotRasmlari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rasmi', models.ImageField(upload_to='Mahsulot/')),
                ('nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Mahsulot', to='product.mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot rasmlari',
                'verbose_name_plural': 'Mahsulot rasmlari',
            },
        ),
        migrations.CreateModel(
            name='mahsulotReyting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reytin', models.IntegerField()),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reytinglar', to='product.mahsulot')),
            ],
            options={
                'verbose_name': 'Mahsulot reytingi',
                'verbose_name_plural': 'Mahsulot reytingi',
            },
        ),
        migrations.CreateModel(
            name='ReviewProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izoh', models.CharField(max_length=250)),
                ('mahsulot_nomi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.mahsulot')),
            ],
        ),
    ]
