# Generated by Django 5.0.6 on 2024-06-27 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviewproducts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewproducts',
            name='time',
            field=models.DateField(auto_now=True),
        ),
    ]
