# Generated by Django 5.0.6 on 2024-07-02 05:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='pochta_kodi',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{1,20}$', 'pochta manzil kiriting')]),
        ),
        migrations.AlterField(
            model_name='checkout',
            name='telefon_raqam',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+998\\d{9}$', '+998 bilan boshlangan raqam kiriting')]),
        ),
    ]
