# Generated by Django 5.0.6 on 2024-07-02 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_checkout_pochta_kodi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product.cart'),
            preserve_default=False,
        ),
    ]
