# Generated by Django 5.0.6 on 2024-07-02 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_checkout_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
    ]
