# Generated by Django 5.0.6 on 2024-06-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Category/')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Category uchun rasm',
                'verbose_name_plural': 'Category uchun rasm',
            },
        ),
        migrations.CreateModel(
            name='LogoRasmlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_link', models.URLField()),
            ],
            options={
                'verbose_name': 'Logo linklari',
                'verbose_name_plural': 'Logo linklari',
            },
        ),
        migrations.CreateModel(
            name='SliderRasm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='Slider/')),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Slider uchun rasm',
                'verbose_name_plural': 'Slider uchun rasm',
            },
        ),
    ]
